;(function () {
;(function () {
(function(){if(!window.b24form){window.b24form=function(e){b24form.forms=b24form.forms||[];b24form.forms.push(e);if(e.ref&&b24form.Loader&&!this.loaded){this.loaded=true;b24form.Loader.loadJs(e.ref,true)}}}if(window.b24form.Loader){return}function e(){this.requested=false;this.queue=[]}e.prototype={run:function(e){e=e||{};var o=e.resources||{};this.queue.push(e.form);if(!this.requested){var t=this.loadApp.bind(this,o.app);this.requested=true;if(o.polyfill&&!this.checkPolyfills()){this.loadJs(o.polyfill,true,t)}else{t()}}this.loadForms()},loadApp:function(e){if(!e){return}window.b24form.App?this.loadForms():this.loadJs(e,true,this.loadForms.bind(this))},loadForms:function(){if(!this.checkPolyfills()){return}if(!window.b24form.App){return}var e=this.queue;this.queue=[];e.forEach(this.loadForm,this)},loadForm:function(e){b24form.App.initFormScript24(e)},checkPolyfills:function(){return window.fetch&&window.Request&&window.Response&&window.Promise&&Object.assign&&Array.prototype.find&&Array.prototype.includes},loadJs:function(e,o,t){var i=document.createElement("SCRIPT");i.setAttribute("type","text/javascript");i.setAttribute("async","");if(o){i.setAttribute("src",e+"?"+(Date.now()/864e5|0));if(t){i.onload=t}this.appendToHead(i)}else{i.appendChild(document.createTextNode(e));this.appendToHead(i)}},appendToHead:function(e){(document.getElementsByTagName("head")[0]||document.documentElement).appendChild(e)}};window.b24form.Loader=new e})();
//# sourceMappingURL=https://testi-site-varserega.ru/bitrix/js/crm/site/form/embed/unit/script.map.js

window.b24form.Loader.run({"form":{"id":"6","sec":"zfgqsf","lang":"ru","address":"https:\/\/testi-site-varserega.ru","views":{"click":{"type":"panel","position":"right","vertical":"bottom"},"auto":{"type":"popup","position":"center","vertical":"bottom","delay":5}},"data":{"language":"ru","design":{"shadow":true,"border":{"bottom":true},"color":{"primary":"#0F58D0","primaryText":"#FFFFFF","text":"#000000","background":"#FFFFFF","fieldBorder":"#00000019","fieldBackground":"#00000014","fieldFocusBackground":"#ffffffff"}},"title":"","desc":"\u041f\u0440\u0435\u0434\u0441\u0442\u0430\u0432\u044c\u0442\u0435\u0441\u044c, \u043f\u043e\u0436\u0430\u043b\u0443\u0439\u0441\u0442\u0430","buttonCaption":"\u041e\u0442\u043f\u0440\u0430\u0432\u0438\u0442\u044c","useSign":true,"date":{"dateFormat":"DD.MM.YYYY","dateTimeFormat":"DD.MM.YYYY HH:MI:SS","sundayFirstly":false},"currency":{"code":"RUB","title":"\u0420\u043e\u0441\u0441\u0438\u0439\u0441\u043a\u0438\u0439 \u0440\u0443\u0431\u043b\u044c","format":"# \u0026#8381;"},"fields":[{"id":"LEAD_NAME","name":"LEAD_NAME","label":"\u0418\u043c\u044f","visible":true,"required":false,"multiple":false,"valueType":null,"type":"name","placeholder":"","value":null,"items":[],"hint":"","hintOnFocus":false,"autocomplete":true,"bigPic":false,"size":null,"contentTypes":null},{"id":"LEAD_LAST_NAME","name":"LEAD_LAST_NAME","label":"\u0424\u0430\u043c\u0438\u043b\u0438\u044f","visible":true,"required":false,"multiple":false,"valueType":null,"type":"last-name","placeholder":"","value":null,"items":[],"hint":"","hintOnFocus":false,"autocomplete":true,"bigPic":false,"size":null,"contentTypes":null},{"id":"LEAD_PHONE","name":"LEAD_PHONE","label":"\u0422\u0435\u043b\u0435\u0444\u043e\u043d","visible":true,"required":true,"multiple":false,"valueType":null,"type":"phone","placeholder":"","value":null,"items":[],"hint":"","hintOnFocus":false,"autocomplete":true,"bigPic":false,"size":null,"contentTypes":null},{"id":"LEAD_EMAIL","name":"LEAD_EMAIL","label":"E-mail","visible":true,"required":false,"multiple":false,"valueType":null,"type":"email","placeholder":"","value":null,"items":[],"hint":"","hintOnFocus":false,"autocomplete":true,"bigPic":false,"size":null,"contentTypes":null}],"agreements":[],"dependencies":[],"captcha":{"service":"google","recaptcha":{"use":false},"yandexCaptcha":{"use":false}}}},"resources":{"app":"https:\/\/testi-site-varserega.ru\/upload\/crm\/6c5\/3yw4bnyp10ogam6y90xnz3drhz1t2myg.js","polyfill":""}});
})();


})();